name: PR

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]
    permissions:
      checks: read
      contents: write
      metadata: write

jobs:
  build-and-lint:
    runs-on: ubuntu-20.04

    container:
      image: golang:1.20

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Make Build
        run: make build -buildvcs=false

      - name: Make Lint
        run: make lint
