name: "pull_request"

on:
  pull_request:
    branches: [ main]
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: golang:1.20
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Make Build
        run: make build

  lint:
    needs: build
    runs-on: ubuntu-20.04
    container:
      image: golang:1.20
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Make Lint
        run: make lint

  docker-lint:
    needs: lint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run hadolint
        uses: hadolint/hadolint-action@v1.5.0
        with:
          dockerfile: Dockerfile
