name: "pull_request"

on:
  pull_request:
    branches: [ main]
    types: [opened, synchronize, reopened]

env:
  GOLANG_VERSION: '1.20'

jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: ${{ env.GOLANG_VERSION }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Make Build
        run: make build

  lint:
    needs: build
    runs-on: ubuntu-20.04
    container:
      image: ${{ env.GOLANG_VERSION }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Make Lint
        run: make lint

  docker-lint:
    needs: lint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Lint Dockerfile
        run: |
          docker pull hadolint/hadolint:latest
          docker run --rm -i hadolint/hadolint hadolint --format json - < Dockerfile
