name: PR

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]
    permissions:
      checks: read
      contents: write
      metadata: write

jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: golang:1.20
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Make git directory safe
        run: git config --global --add safe.directory '*'
      - name: Make Build
        run: make build

  lint:
    needs: build
    runs-on: ubuntu-20.04
    container:
      image: golang:1.20
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Make git directory safe
        run: git config --global --add safe.directory '*'
      - name: Make Lint
        run: make lint

  docker-lint:
    needs: lint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Lint Dockerfile
        run: |
          docker pull hadolint/hadolint:latest
          docker run --rm -i hadolint/hadolint hadolint --format json - < Dockerfile
